### ISSUE TITLE
does jnr-posix work on osx_arm64? 

### ISSUE THREAD

**Issue by reevesg** [jnr/jnr-posix#175]
I get "could not load FFI provider jnr.ffi.provider.jffi.Provider"

Here is my simple repo

```
import jnr.posix.POSIX;
import jnr.posix.POSIXFactory;

public class JNRPosixTest {
  public static void main(String[] args) throws Exception {
    final POSIX posix = POSIXFactory.getNativePOSIX();
  }
}
```

Built with... 

`javac -cp jnr-constants-0.10.3.jar:jnr-ffi-2.2.12.jar:jnr-posix-3.1.15.jar  JNRPosixTest.java`

Run with... 

`java -cp jnr-constants-0.10.3.jar:jnr-ffi-2.2.12.jar:jnr-posix-3.1.15.jar:. JNRPosixTest` 

And I get 

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
        at jnr.ffi.provider.InvalidProvider$1.loadLibrary(InvalidProvider.java:49)                 
        at jnr.ffi.LibraryLoader.load(LibraryLoader.java:420)                 
        at jnr.posix.POSIXFactory$DefaultLibCProvider$SingletonHolder.<clinit>(POSIXFactory.java:307)
        at jnr.posix.POSIXFactory$DefaultLibCProvider.getLibC(POSIXFactory.java:335)                 
        at jnr.posix.BaseNativePOSIX.<init>(BaseNativePOSIX.java:41)
        at jnr.posix.MacOSPOSIX.<init>(MacOSPOSIX.java:16)      
        at jnr.posix.POSIXFactory.loadMacOSPOSIX(POSIXFactory.java:153)
        at jnr.posix.POSIXFactory.loadNativePOSIX(POSIXFactory.java:121)
        at jnr.posix.POSIXFactory.getNativePOSIX(POSIXFactory.java:75)
        at jnr.posix.POSIXFactory.getNativePOSIX(POSIXFactory.java:85)
        at JNRPosixTest.main(JNRPosixTest.java:7)
Caused by: java.lang.NoClassDefFoundError: com/kenai/jffi/Type
        at jnr.ffi.provider.jffi.NativeRuntime.jafflType(NativeRuntime.java:213)
        at jnr.ffi.provider.jffi.NativeRuntime.buildTypeMap(NativeRuntime.java:96) 
        at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:77)
        at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:49)
        at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:73)
        at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:60)
        at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:68)
        at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:57)
        at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
        at jnr.ffi.LibraryLoader.create(LibraryLoader.java:89)
        at jnr.posix.POSIXFactory$DefaultLibCProvider$SingletonHolder.<clinit>(POSIXFactory.java:292)
        ... 8 more
Caused by: java.lang.ClassNotFoundException: com.kenai.jffi.Type
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 25 more
```

Architecture details: 
``` 
uname -a 
Darwin REDACTED 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64
```

**Comment by reevesg** [comment]
nvm - I found the other issue and added the extra dependencies https://github.com/jnr/jnr-ffi/issues/118
