### ISSUE TITLE
loading native POSIX failed 

### ISSUE THREAD

**Issue by erikdraven** [jnr/jnr-posix#40]
Hi,

I seem to be running into an issue when I run my app (using jnr-posix) from a jetty instance inside eclipse. It fails to load the native implementation, and falls back to the java implementation (see traceback below). It does seem to work if you run it from a shell (I'm on ubuntu 12.04 64-bit). Do you have a workaround for this?

Thanks!

```
Failed to load native POSIX impl; falling back on Java impl. Stacktrace follows.
java.lang.IncompatibleClassChangeError: Found interface org.objectweb.asm.ClassVisitor, but class was expected
	at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:74)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:59)
	at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:43)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:265)
	at jnr.ffi.Library.loadLibrary(Library.java:123)
	at jnr.posix.POSIXFactory$DefaultLibCProvider$SingletonHolder.<clinit>(POSIXFactory.java:219)
	at jnr.posix.POSIXFactory$DefaultLibCProvider.getLibC(POSIXFactory.java:223)
	at jnr.posix.BaseNativePOSIX.<init>(BaseNativePOSIX.java:36)
	at jnr.posix.LinuxPOSIX.<init>(LinuxPOSIX.java:18)
	at jnr.posix.POSIXFactory.loadLinuxPOSIX(POSIXFactory.java:95)
	at jnr.posix.POSIXFactory.loadNativePOSIX(POSIXFactory.java:69)
	at jnr.posix.POSIXFactory.loadPOSIX(POSIXFactory.java:38)
	at jnr.posix.LazyPOSIX.loadPOSIX(LazyPOSIX.java:35)
	at jnr.posix.LazyPOSIX.posix(LazyPOSIX.java:31)
	at jnr.posix.LazyPOSIX.getcwd(LazyPOSIX.java:451)
```

**Comment by headius** [comment]
You have a conflict with an earlier version of the ASM library (perhaps pre-4.0 I think?) Someone's pulling in an old version and we build with a newer version.

**Comment by erikdraven** [comment]
Cool, yeah, this is a really old ticket. I haven't been up to speed, about the recent changes on this. Will give it a go...
