### ISSUE TITLE
Java 8 breakage

### ISSUE THREAD

**Issue by nsayer** [jnr/jnr-posix#76]
We use jnr-posix to relinquish root privileges after opening server sockets (that is, listening sockets < 1024). With java 8, we get

`java.lang.IllegalStateException: getpwnam unimplemented is not implemented in jnr-posix
	at jnr.posix.util.DefaultPOSIXHandler.unimplementedError(DefaultPOSIXHandler.java:28)
	at jnr.posix.JavaPOSIX.getpwnam(JavaPOSIX.java:176)
	at jnr.posix.LazyPOSIX.getpwnam(LazyPOSIX.java:198)`

This worked fine in previous JREs.

**Comment by nsayer** [comment]
Our code is fairly straightforward:

`POSIX posix = POSIXFactory.gePosix();
Passwd pwd = posix.getpwnam(user);`

That last line is the one that throws the exception.

**Comment by headius** [comment]
That's very strange. It is possible that changed Java method dispatch rules in Java 8 are causing to to call a wrong overload? We use getpwnam in JRuby on Java 8 and it works fine.

**Comment by nsayer** [comment]
Bueller?

**Comment by nsayer** [comment]
We're not doing anything particular to prevent the native code running. The only difference is the JDK version.
