### ISSUE TITLE
pipe is not implemented in jnr-posix

### ISSUE THREAD

**Issue by jiffypop23** [jnr/jnr-posix#83]
Trying to create a Process but am getting this error:

```
Exception in thread "thread" java.lang.IllegalStateException: pipe is not implemented in jnr-posix
at jnr.posix.util.DefaultPOSIXHandler.unimplementedError(DefaultPOSIXHandler.java:28)
at jnr.posix.JavaPOSIX.pipe(JavaPOSIX.java:636)                                                                                                                                        at jnr.posix.LazyPOSIX.pipe(LazyPOSIX.java:500)                                                                                                                                        at jnr.process.ProcessBuilder.start(ProcessBuilder.java:65)
```

```
ProcessBuilder pB = new ProcessBuilder().command("command here");
Process p = pB.start();
```

Mac OSX 10.11.6, Java 1.8.0_101
What causes this?

**Comment by nirvdrum** [comment]
I'm not sure how you've loaded jnr-posix. You're code example doesn't really show. But, based on the stack trace it looks like you're not using a native POSIX implementation. Since you're using the Java-based one, there's a lot of POSIX calls that either aren't implemented or not implemented fully. The `JavaPOSIX` handler really is a best-effort, but shouldn't be relied upon if you can avoid it. Try loading a native handler.

**Comment by jiffypop23** [comment]
So I have no clue what's different (I didn't touch my code at all), but it works now... weird isolated error maybe?
